name: Enable Auto Merge Action
description: |
  Turns on auto merge on a pull request. Note that the repository must first allow this feature.
inputs:
  github-pat:
    description: The GitHub token used to authenticate.
    required: true
  node-id:
    description: The pull request Node ID
    required: false
    default: ${{ github.event.pull_request.node_id }}
  merge-method:
    description: One of "MERGE", "SQUASH", "REBASE".
    required: false
    default: MERGE
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: my-script
      with:
        github-token: ${{ inputs.github-pat }}
        retries: 3
        script: |
          return await github.graphql(
            `mutation enableAutoMerge($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod) {
               enablePullRequestAutoMerge(input: {
                 pullRequestId: $pullRequestId,
                 mergeMethod: $mergeMethod,
               }) {
                 pullRequest {
                   id,
                   autoMergeRequest {
                     enabledAt
                   }
                 }
               }
            }`,
            {
              pullRequestId: "${{ inputs.node-id }}",
              mergeMethod: "${{ inputs.merge-method }}"
            }
          );
