name: Enable Auto Merge Action
description: |
  Turns on auto merge on a pull request. Note that the repository must first allow this feature.
inputs:
  github-token:
    description: |
      The GitHub token used to authenticate. This should be a PAT.
    required: true
  pull-request:
    description: |
      The pull request Node ID. Defaults to the picking up from the context, when available.
    required: false
    default: ${{ github.event.pull_request.node_id }}
  merge-method:
    description: One of "MERGE", "SQUASH", "REBASE". Defaults to "MERGE"
    required: false
    default: "MERGE"
runs:
  using: "docker"
  image: Dockerfile
